### PR TITLE
fix: match rebranded syles

### LINKED ISSUE #215: bug: wrong styling
**Describe the bug**
A bunch of things are not styled like they should be.

1. **Embed author** (font-weight)
how it is: `{font-weight: 700}`
image
how it should be: `{font-weight: 600}`
image

2. **Message author** (font-size, letter-spacing)
how it is: `{font-size:1.1em; letter-spacing: 0.5px}`
image
how it should be: `{font-size: 1rem;}` (discord uses default spacing)
image

3. **Embed footer** 
how it is:
image
how it should be:
image

4. **Message reply author**
how it is:
image
how it should be:
image

Im using rule overrides with `!important` in my project to fix these for now<br>

### PR DESCRIPTION
**Pull request by DarkGuy10**
fixes #215

### CODE REVIEW

**Comment by DarkGuy10** [comment]
The font imports in `packages/core/src/components/discord-messages/discord-messages.css` still need to be updated once the CDN assets are fixed

**Comment by favna** [comment]
> The font imports in `packages/core/src/components/discord-messages/discord-messages.css` still need to be updated once the CDN assets are fixed

New fonts are available:
https://cdn.skyra.pw/whitney-font/v2/Semibold.woff
https://cdn.skyra.pw/whitney-font/v2/Medium.woff
https://cdn.skyra.pw/whitney-font/v2/Book.woff
https://cdn.skyra.pw/whitney-font/v2/Bold.woff

**Comment by DarkGuy10** [comment]
:+1: Updated and pushed, this PR is ready for review now

**Comment by DarkGuy10** [comment]
@favna - sama?

**Review by favna — APPROVED** [review]

**Comment by favna** [comment]
Released in [v3.1.1](https://github.com/skyra-project/discord-components/releases/tag/v3.1.1)

**Pull request merged**
