### PR TITLE
chore(buttons): update new types colors

### PR DESCRIPTION
**Pull request by Mateo-tem**
Updates the colors of the button types to the new Discord ones.

**Updated Button Types:**
- Success
- Destructive
- Secondary

### CODE REVIEW

**Review by favna — CHANGES_REQUESTED** [review]
This is wrong. When using the devtools inspector you can see the color of the destructive button is `rgb(237, 66, 69)` which translates to `#ed4245`

**Comment by favna** [comment]
Click to expand to see screenshots of all colours:

<details>
<summary>Non-hovered colours for all styles</summary>

image
image
image
image



</details>


<details>
<summary>Hovered colours for all styles</summary>

image
image
image
image


</details>

**Comment by Mateo-tem** [comment]
So, what I'm supposed to change? Or all is invalid?

**Comment by favna** [comment]
> So, what I'm supposed to change? Or all is invalid?

It's all invalid but rather than straight up closing I wanted to give you a chance to react. For example I'm not sure where you got these hex codes from.

**Comment by Mateo-tem** [comment]
Oh, well I noticed that some of the colors on Discord were changed, for example, the buttons. So, I used a tool to detect hex codes of an image and I made this PR. It may sound silly, but I just wanted to confirm the color difference.

**Comment by favna** [comment]
Well I'm not sure what tool you used but I guess it was off by a bit because dev tools shows the actual CSS. To be fair, the 2 tools I know are ShareX and Color Picker (part of PowerToys) and they both report incorrect CSS colours.

These days Discord doesn't allow you use use `Ctrl + Shift + I` to open dev tools in their Stable clients (it is still enabled in Canary, I don't have PTB installed to check) but if you want to re-enable it in Stable then follow these instructions:
image


Anyway that all said, I'm gonna close this PR now.

**Comment by Mateo-tem** [comment]
Well, thanks, and sorry because I was wrong.

**Pull request closed without merging**
