### PR TITLE
Add support for clan tags

### PR DESCRIPTION
**Pull request by mezotv**
This adds support for clan tags and is currently a work in progress.

Todo:
- [x] Add message support
- [x] Add reply support
- [x] Add compact mode support
- [x] Allow custom + default tag icons
- [x] Clean up css
- [x] Add hover state (optional)

grafik

### CODE REVIEW

**Comment by mezotv** [comment]
Todo:
- [ ] Add message support
- [ ] Add reply support
- [ ] Add compact mode support
- [ ] Allow custom + default tag icons
- [ ] Clean up css
- [ ] Add hover state (optional)

**Comment by mezotv** [comment]
I somehow also need to figure out how move the tag to the left of the name for replies and compact mode. Perhaps you can help there @favna?

**Comment by mezotv** [comment]
Clan tags now work with discords default ones and room to upload your own.

I also added an example featuring @dpaulos6 (who did all the css) and me!

image
image


*dislclaimer the names for the clan icons arent all accurate since discord doesnt really have a name for them.*

**Comment by favna** [comment]
wtf...

**Comment by mezotv** [comment]
Welp....

**Comment by favna** [comment]
Merged in #463. Git messed up because the head branch of this PR was your main branch instead of a custom branch. Really advice making new branches in the future. Also makes synching your own fork much easier.

**Comment by favna** [comment]
Released in v4.0.0-alpha.33 (actually alpha 32 but I made an oopsie)

**Pull request closed without merging**
